# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '-p:Version=$(buildVersion) --no-incremental -c Release -t:Clean'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\Properties\PublishProfiles'
    Contents: '**\*.pubxml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\PublishProfiles'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '--configuration $(BuildConfiguration) --no-restore --no-build --output $(Build.Repository.LocalPath)/publish'
    arguments: '$(Build.Repository.LocalPath)/$(projectName)/$(projectName).csproj'
    zipAfterPublish: false
    workingDirectory: '$(Build.Repository.LocalPath)/'